// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Vitor da Silva",
            "email": "vitsilva@furb.br"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/RestAPIFurb/comandas": {
            "get": {
                "description": "Retorna todas as comandas cadastradas",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comandas"
                ],
                "summary": "Lista todas as comandas",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Comanda"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria uma nova comanda com os dados fornecidos",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comandas"
                ],
                "summary": "Cria nova comanda",
                "parameters": [
                    {
                        "description": "Dados da nova comanda",
                        "name": "comanda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Comanda"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/model.Comanda"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/RestAPIFurb/comandas/{id}": {
            "get": {
                "description": "Retorna uma comanda pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comandas"
                ],
                "summary": "Busca comanda por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Comanda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Comanda"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Atualiza uma comanda existente pelo ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comandas"
                ],
                "summary": "Atualiza comanda existente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Comanda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados para atualizar a comanda",
                        "name": "comanda",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Comanda"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Comanda"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Remove uma comanda existente pelo ID (Autenticação JWT necessária)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comandas"
                ],
                "summary": "Remove comanda existente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID da Comanda",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/RestAPIFurb/docs/models": {
            "get": {
                "description": "Modelos auxiliares para documentação do Swagger",
                "tags": [
                    "Docs"
                ],
                "summary": "Modelos usados na API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LoginInput"
                        }
                    }
                }
            }
        },
        "/RestAPIFurb/login": {
            "post": {
                "description": "Gera um token JWT simples para teste",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Autenticação"
                ],
                "summary": "Gera token JWT",
                "parameters": [
                    {
                        "description": "Dados do usuario",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Comanda": {
            "type": "object",
            "required": [
                "idUsuario",
                "nomeUsuario",
                "produtos",
                "telefoneUsuario"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "idUsuario": {
                    "type": "integer"
                },
                "nomeUsuario": {
                    "type": "string"
                },
                "produtos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Produto"
                    }
                },
                "telefoneUsuario": {
                    "type": "string"
                }
            }
        },
        "model.ComandaResumoDTO": {
            "type": "object",
            "properties": {
                "idUsuario": {
                    "type": "integer"
                },
                "nomeUsuario": {
                    "type": "string"
                },
                "telefoneUsuario": {
                    "type": "string"
                }
            }
        },
        "model.ComandaUpdateDTO": {
            "type": "object",
            "properties": {
                "idUsuario": {
                    "type": "integer"
                },
                "nomeUsuario": {
                    "type": "string"
                },
                "produtos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ProdutoDTO"
                    }
                },
                "telefoneUsuario": {
                    "type": "string"
                }
            }
        },
        "model.LoginInput": {
            "type": "object",
            "properties": {
                "senha": {
                    "type": "string",
                    "example": "123456"
                },
                "usuario": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "model.Produto": {
            "type": "object",
            "required": [
                "nome",
                "preco"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "preco": {
                    "type": "number"
                }
            }
        },
        "model.ProdutoDTO": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "preco": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "REST API Comandas FURB",
	Description:      "Documentação Swagger da API de comandas da prova de suficiência Web II.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
